"""empty message

Revision ID: 48a2179822a5
Revises: 
Create Date: 2019-04-30 17:25:24.332531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a2179822a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('grounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('hasMusic', sa.Boolean(), nullable=False),
    sa.Column('hasWifi', sa.Boolean(), nullable=False),
    sa.Column('hasToilet', sa.Boolean(), nullable=False),
    sa.Column('hasEatery', sa.Boolean(), nullable=False),
    sa.Column('hasDressingRoom', sa.Boolean(), nullable=False),
    sa.Column('hasLighting', sa.Boolean(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groundactivities',
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Enum('easy_training', 'football', 'hockey', 'basketball', 'skating', 'ice_skating', 'workout', 'yoga', 'box', name='activity'), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['grounds.id'], ),
    sa.PrimaryKeyConstraint('ground_id', 'activity')
    )
    op.create_table('bucketitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketitems')
    op.drop_table('groundactivities')
    op.drop_table('buckets')
    op.drop_table('users')
    op.drop_table('grounds')
    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
